# Generated by Django 2.0.3 on 2018-04-27 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=25)),
                ('units', models.CharField(choices=[(0, 'Imperial'), (1, 'Metric')], max_length=1)),
                ('notificationType', models.CharField(choices=[(0, 'email'), (1, 'phone'), (2, 'web')], max_length=1)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='drinklog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='time',
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 13, 36, 43, 298386)),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 13, 36, 43, 300387)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 13, 36, 43, 296385)),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
