# Generated by Django 2.0.3 on 2018-04-27 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20180427_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkinformation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='exerciseinformation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='drinkinformation',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 25, 638402)),
        ),
        migrations.AlterField(
            model_name='exerciseinformation',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 25, 640403)),
        ),
        migrations.AlterField(
            model_name='foodinformation',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 25, 637402)),
        ),
    ]
