# Generated by Django 2.0.3 on 2018-04-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20180419_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notificationType',
            field=models.CharField(choices=[('EMAIL', 'email'), ('PHONE', 'phone'), ('WEB', 'web')], default='EMAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='units',
            field=models.CharField(choices=[('IMPERIAL', 'imperial'), ('METRIC', 'metric')], default='IMPERIAL', max_length=10),
        ),
    ]
