# Generated by Django 2.0.3 on 2018-04-27 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20180427_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 41, 435766)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 41, 436767)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 14, 6, 41, 433764)),
        ),
    ]
