# Generated by Django 2.0.3 on 2018-04-19 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20180419_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 11, 2, 36, 323828)),
        ),
    ]
