# Generated by Django 2.0.3 on 2018-04-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20180419_0112'),
        ('Tracker', '0002_auto_20180419_0132'),
    ]

    operations = [
    ]
