# Generated by Django 2.0.3 on 2018-04-27 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_auto_20180427_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 19, 48, 33, 346372)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 19, 48, 33, 346847)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 27, 19, 48, 33, 345901)),
        ),
    ]
