# Generated by Django 2.0.3 on 2018-04-29 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_auto_20180429_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 41, 51, 789202)),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 41, 51, 792210)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 41, 51, 793213)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 41, 51, 790706)),
        ),
    ]
