# Generated by Django 2.0.3 on 2018-04-29 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_auto_20180429_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 59, 7, 67940)),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 59, 7, 69443)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 59, 7, 70446)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 59, 7, 68942)),
        ),
    ]
