# Generated by Django 2.0.3 on 2018-04-29 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_auto_20180429_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 11, 24, 747057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 11, 24, 748561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 11, 24, 749063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 20, 11, 24, 748060, tzinfo=utc)),
        ),
    ]
