# Generated by Django 2.0.3 on 2018-04-19 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinklog',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='time',
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 13, 36, 57, 446923)),
        ),
        migrations.AlterField(
            model_name='drinklog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 13, 36, 57, 446923)),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 19, 13, 36, 57, 445921)),
        ),
    ]
